### ISSUE TITLE
Expose only `Track()` to users and internally decide between `SingleTrack` and `PartialTrack`?

### ISSUE THREAD

**Issue by sehilyi** [manzt/gos#12]
I am wondering if it makes sense to expose `gos.Track()` only to users instead of the additional `gos.PartialTrack()`. I think whenever a user uses `overlay` `alignment` with `tracks`, we can internally consider this as `PatialTrack` so that users do not have to manually select between `SingleTrack` and `PartialTrack`.

```js
bar_overview = bar_base.properties(
    width=300, height=300,
    alignment='overlay',
    tracks=[
        gos.Track(), // since overlay alignment is used with tracks, this is PartialTrack
        gos.Track().mark_brush().encode(x=gos.Channel(linkingId='detail-1')),
        gos.Track().mark_brush().encode(x=gos.Channel(linkingId='detail-2'))
    ]
)
```

**Comment by manzt** [comment]
I think this is a good idea, but unfortunately the types are distinct. `Track` currently inherits from `gosling.schema.Track` so it cannot be instantiated without arguments -- this is all autogenerated code that does validation. `gos.Track` just inherits some additional "mixins" that allow method chaining for assiging properties to the underlying `gosling.schema.Track`. 

Another option would be to export a singleton of `PartialTrack` for use in this situation:

```python
# gosling/api.py
track = PartialTrack()

# example.py
bar_overview = bar_base.properties(
    width=300, height=300,
    alignment='overlay',
    tracks=[
        gos.track, // since overlay alignment is used with tracks, this is PartialTrack
        gos.track.mark_brush().encode(x=gos.Channel(linkingId='detail-1')),
        gos.track.mark_brush().encode(x=gos.Channel(linkingId='detail-2'))
    ]
)
```

With that said, there is likely a way to make `Track` more "magical" and I'll take a look.

**Comment by manzt** [comment]
Another option would be to have a `gos.track()` util that inspects the arguments to decide whether to return a `Track` vs `PartialTrack` instance.

```python
bar_overview = gos.track(data=data).properties(
    width=300, height=300,
    alignment='overlay',
    tracks=[
        gos.track(), # since overlay alignment is used with tracks, this is PartialTrack
        gos.track().mark_brush().encode(x=gos.Channel(linkingId='detail-1')),
        gos.track().mark_brush().encode(x=gos.Channel(linkingId='detail-2'))
    ]
)
````

The less magic the better IMO

**Comment by sehilyi** [comment]
Closing this for now since I think this is addressed by https://github.com/manzt/gos/pull/19#issue-716126395
