### ISSUE TITLE
Auto-cast `gos.Track` to `gos.View` in concat utilities

### ISSUE THREAD

**Issue by manzt** [manzt/gos#22]
It seems like this might be a common pattern that we could do automatically in the view concat methods.

```python
gos.horizontal(track.view(), track2.view(), view)
# vs
gos.horizontal(track, track2, view) # auto-calleds track.view() internally
```

_Originally posted by @manzt in https://github.com/manzt/ipygosling/pull/19#discussion_r693127142_

**Comment by sehilyi** [comment]
I think we can close this? https://github.com/manzt/gos/pull/28
